- e3nn/kernel.py
- e3nn/point/kernelconv.py
- e3nn/point/operations.py
- tests/kernel_test.py
- tests/point/kernelconv_test.py
This introduces a new feature KernelConv.
Adds custom forward and backward function for convolution.
Adds automatic backwards (normal pytorch behavior) Kernel. I suggest we use this by default. Right now it is listed as a separate function which has a corresponding test case.
Although it is only for a QM9 style problem (i.e. shape of input) KernelConv combines the two operations just as was requested in the optimization project.
> Added KernelConv, reintroduced kernel without KernelFn, reintroduced ConvolutionFn

- e3nn/kernel.py
- e3nn/point/kernelconv.py
- e3nn/point/operations.py
- tests/kernel_test.py
- tests/point/kernelconv_test.py
I think @mariogeiger might not like that there is a keyword argument. The biggest offender is probably the new convolution. Let me know if you think I should change it.
Another option is to instead create an attribute of the object which says whether or not to use custom_backward or not. I didn't like this as much since it is less flexible; however, it is more "object oriented."
The introduction of KernelConv solves issue #18 
--
The default behavior is to use custom backward for KernelConv and the automatic backward for kernel and convolution.
When using KernelConv with custom_backward=True in qm9 I was able to do 1000 molecule epochs in 11 seconds. When using custom_backward=False in qm9 the same number of molecules were iterated over in nearly 18 seconds.
It seems the behavior of these …
> Introduced KernelConv, Introduced custom backward pass options for kernel and convolution and KernelConv

- e3nn/networks.py
I found myself recreating this network over and over again, so I though it might be a nice default to have. Please feel free to modify, such moving activations and radial models as keywords.
> added a simple default convolutional network with gated activations

- e3nn/batchnorm.py
- tests/batchnorm_test.py
- changed the order of indices `[batch, features, spacial]` -> `[batch, spacial, features]`
- complete docstring
> Change the order of indices in Batchnorm

- e3nn/kernel.py
- e3nn/point/kernelconv.py
@L-sky introduced a time ago a distinction between the normalizations for r=0 and r>0.
I propose to distinguish as well the weight for r=0 and r>0.
- r>0 : we use the radial functions.
- r=0 : I propose to use separate weights.
> Separate weights for special case r=0

- e3nn/kernel.py
- e3nn/networks.py
- e3nn/o3.py
- e3nn/point/kernelconv.py
- e3nn/rs.py
#43
Changed the signature of `o3.selection_rule` to
```python
o3.selection_rule(l_1, p_1, l_2, p_2)
```
This allow the user to customize `get_l_output` of `tensor_product` based on the parity.
> Include parity in selection rule

- e3nn/networks.py
- e3nn/tensor_product.py
- tests/tensor_product_test.py
Simple and intuitive re-definition of
`LearnableTensorProduct(Rs_in1, Rs_in2, Rs_out)`
You set the inputs and output and it will learn a mapping using a linear combination of tensor products.
I removed `Bispectrum` since it look very specific and it not used in the repository. I think if you use it you have to define it in the project where you use it.
> LearnableTensorProduct

- e3nn/networks.py
- e3nn/point/data_helpers.py
- tests/tensor/spherical_tensor_test.py
Make `GatedParityConvNetwork` take general arguements (so it can be used with `e3nn.point.message_passing.Convolution`.
Correct `e3nn.point.data_helpers.neighbor_list_and_relative_vec` to give neighbors within distance D (previously was 2 * D + skin, set skin == 0.0 and divide sphere radius by 2).
> Various fixes to network and data_helpers

- e3nn/point/depthwise.py
- tests/point/depthwise_tests.py
also added `Rs_mid1` and `Rs_mid2`. note that I also had to add scalars to the `Rs_mid1` and `Rs_mid2` so that GatedBlock would be happy.
> test of depthwise with message_passing.Convolution

- e3nn/kernel.py
- e3nn/point/depthwise.py
- e3nn/point/message_passing.py
- e3nn/point/operations.py
- tests/kernel_test.py
- tests/point/depthwise_tests.py
- tests/point/message_passing_test.py
Add ability to use "groups" for convolution and the ability to have either a single `Kernel` applied to each group OR use a `GroupKernel` which applies a different `Kernel` to each group. The goal of `DepthwiseConvolution` is to use groups to drastically shrink the amount of terms in the Kernel tensor product. `DepthwiseConvolution` can be used with both `Kernel` or `GroupKernel` as `Convolution` type modules will detect whether a group dimension is present in the given kernel output.
> GroupKernel and DepthwiseConvolution

- .gitignore
I built e3nn with CUDA support "in-place", meaning that it puts the shared library `cuda_rsh.cpython-38-x86_64-linux-gnu.so` in the `e3nn` directory. This PR makes git ignore the built shared libraries in the source directory.
> Ignore shared libraries built in place.

- examples/point/tetris_torch_geo.py
Hi, I have a question and a potential solution for my question in this PR.
https://github.com/e3nn/e3nn/blob/4c12f848c07e5d1b149ff9a68f525c7e2e6f885b/examples/point/tetris_torch_geo.py#L49
https://github.com/e3nn/e3nn/blob/4c12f848c07e5d1b149ff9a68f525c7e2e6f885b/examples/point/tetris_torch_geo.py#L65
I was modeling my code on this `tetris_torch_geo.py` example.
I tried to change `Rs_sh` in my code, but the tensors were not correctly-sized until I made `sh` match.
I am guessing that `sh` is defined here (and not left as `None`, which is handled in `WTPConv.forward` based on `Rs_sh`) because it's being pre-calculated and re-used in each convolution layer.
If my understanding is correct, I'd like to add a code comment that mentions the use of pre-computation, and perhaps use `Rs_sh` …
> Clarify Rs_sh / sh in tetris example.

- .github/workflows/pull_request.yml
- .github/workflows/push.yml
This updates CI to un-pin pip < 20.3. The dependencies have been fixed, as described in this issue: https://github.com/rusty1s/pytorch_geometric/issues/1876
> Try pip 20.3 with updated dependencies.

- e3nn/point/data_helpers.py
- tests/point/data_helpers_test.py
This PR updates the `DataNeighbors` data helpers to improve a few things:
- Use the newer linear-scaling [ASE neighbor lists](https://wiki.fysik.dtu.dk/ase/ase/neighborlist.html) instead of the older, quadratic ones (which are used by default in the `ase.neighborlist.NeighborList` class)
- Use ASE consistently for both periodic and non-periodic systems (rather than using `pymatgen` for periodic systems)
- Expose ASE's support for partial periodic boundary conditions such as surfaces that are periodic in two-of-three cell vectors
- Avoid the allocation of intermediate `ase.Atoms`/`pymatgen.Structure` objects to improve dataloading efficiency
- Add `DataNeighbors.from_ase`
- Adds and updates relevant tests
I've concentrated all the neighbor finding into `DataNeighbors` and …
> Unified `DataNeighbors` using newer ASE neighbor lists

- e3nn/point/data_helpers.py
- tests/point/data_helpers_test.py
My previous PR in #162 had broken the ability to autograd back to positions through displacements (the `edge_attrs` of the graph) which is needed, for example, in https://github.com/e3nn/e3nn/blob/master/examples/point/atomic_forces.py. 
I've fixed the issue (`atomic_forces.py` runs now) and added a simple test for gradients on positions when using `DataNeighbors`.
> Compute displacements in way that autograd can handle (fix #162)

- ChangeLog.md
- e3nn/nn/normact.py
Fix `NormActivation` on GPU by making `epsilon` a buffer.
e3nn test suite (CPU), running a model that uses it on GPU (thanks @simonbatzner).
> Fix `NormActivation` on GPU

- e3nn/io/spherical_tensor.py
These three functions now return a tensor of correct dimension of zeros when given an empty list of vectors to convert
* from_geometry_adjusted
* from_geometry_global_rescale
* from_samples_on_s2
It's just a simple check if the list of vectors is empty, if yes, it returns a torch.Tensor of 0's with the dimension of the SphericalTensor. 
Previously it broke for empty lists. 
I ran pytest on the tests directory 
I ran flake8 on my files 
I tested that all three actually gives 0-tensors. 
- [ x] I have read the [**CONTRIBUTING**](https://github.com/e3nn/e3nn/blob/main/CONTRIBUTING.md) document.
- [ x] My code follows the code style of this project.
- [x ] All new and existing tests passed.
> Spherical tensor returns 0 when given an empty list of vectors to convert

- ChangeLog.md
- e3nn/nn/models/gate_points_2101.py
- e3nn/util/eval_code.py
Use `tempfile.NamedTemporaryFile` in `eval_code` to ensure that temporary files contained generated code get cleaned up.
The previous code used `tempfile.mkstemp()`, which does not clean up its created files at all and as a result can create many, many temporary files (two for each `TensorProduct`) that don't typically get cleaned up till system restart.
The `e3nn` test suite.
> Codegen File Cleanup

- e3nn/o3/tensor_product.py
Small change to make TorchScript codegen templates have the same indentation as surrounding code and then remove extra indentation using [`textwrap.dedent`](https://docs.python.org/3/library/textwrap.html#textwrap.dedent). Makes `TensorProduct` much easier to read.
> Cleaner codegen with `textwrap.dedent`

- ChangeLog.md
- e3nn/o3/cartesian_spherical_harmonics.py
- e3nn/util/jit.py
- e3nn/util/test.py
- tests/o3/cartesian_spherical_harmonics_test.py
TorchScript can't handle direct calls to `o3.spherical_harmonics` because of the irreps parameter/irreps handing and control flow inside of it. It can, however, be traced without issue. This PR makes doing that simpler.
Unrelatedly, this PR adds an `in_place` argument to the `e3nn.util.jit` compilation functions. Because they recursively compile submodules, they currently affect the module that is passed to them. This addition maintains this behavior (`in_place = True` by default) but allows the user to choose to have a copy of the module made first.
Some modules should be `@compile_mode('script')` but want to call `spherical_harmonics` and currently can't. By making it a submodule with appropriate compilation decorators, tracing through `spherical_harominics` inside of a script-mode …
> `SphericalHarmonics` module

- ChangeLog.md
- e3nn/math/normalize_activation.py
- e3nn/nn/gate.py
- e3nn/o3/cartesian_spherical_harmonics.py
- e3nn/util/_argtools.py
- e3nn/util/jit.py
- tests/o3/cartesian_spherical_harmonics_test.py
Bureaucratic fixes for running on GPU:
- make `normalize2mom` respect current device
- make `Gate` keeps its activations as submodules so they `.to` with it
- add `_get_device`
- Make `spherical_harmonics` a wrapper for `SphericalHarmonics` 
- make `SphericalHarmonics` scriptable so that it doesn't trace and pick up tensors on the wrong device
e3nn test suite, our code's tests (which were failing before on GPU)
> Some fixes for `device` on GPU

- .github/workflows/tests.yml
- ChangeLog.md
- e3nn/nn/models/gate_points_2101.py
- e3nn/nn/models/gate_points_2102.py
- e3nn/nn/models/v2103/conv_points_in_out.py
- e3nn/nn/models/v2103/gate_points_message_passing.py
- e3nn/nn/models/v2103/gate_points_networks.py
- e3nn/nn/models/v2103/points_convolution.py
- e3nn/o3/cartesian_spherical_harmonics.py
- e3nn/o3/irreps.py
- e3nn/util/jit.py
- e3nn/util/test.py
- examples/tensor_product_benchmark.py
- examples/tensor_product_profile.py
- examples/tetris_gate.py
- setup.cfg
- tests/math/linalg_test.py
- tests/nn/models/gate_points_2101_test.py
- tests/nn/models/gate_points_2102_test.py
- tests/util/test_jit.py
While working on #227, I noticed that the flake8 configuration used by CI is not stored in the typical place for package/tool configurations (either `setup.cfg` or `.flake8`; [flake8 does not support `pyproject.toml`](https://gitlab.com/pycqa/flake8/-/issues/428)).
I talked with @mariogeiger and we decided to create a package-wide configuration for flake8 that developers can use locally, without needing to copy all the settings from the CI config.
This means that users/developers can simply run `flake8` in the repository root, to check for style issues.
While doing this, I also simplified the flake8 rules from the CI configuration and fixed the small number of issues that appeared. Nothing major has changed -- just normalized style.
One note for context: I have found from working with …
> Create global flake8 configuration.

- e3nn/nn/gate.py
> Fix typo (there are three conditions instead of two).

- ChangeLog.md
- e3nn/o3/tensor_product/tensor_product.py
Matches argument names for tensor products with the equations below them. I chose to match the code to the equations instead of the other way around because there were more equations than lines of code, but the other way would also be viable if that is preferred.
(Please feel free to reject this PR if you don't think it's an improvement!)
Improves consistency in terminology.
Tests passed locally.
> Use x, y instead of x1, x2 to match the math.

- ChangeLog.md
- e3nn/math/soft_one_hot.py
- tests/math/soft_one_hot_test.py
Add Bessel Basis to ```math.soft_one_hot_linspace```
Added ```bessel``` as an option for basis in ```math.soft_one_hot_linspace```, as proposed in [1]. Note that due to the 1/x behavior of Bessel it cannot be properly normalized. I added this to the docstring. The is some ambiguity whether or not to let the denominator in the basis be ```1/x``` or ```1/(x/c``` where ```c=end-start``` is the length of the interval the basis is computed over. Following [1] I went with the former. 
[1] https://arxiv.org/abs/2003.03123
Bessel Basis performs well in practice. 
I ran pytest tests and add the Bessel basis to the soft_one_hot_tests
- [ x] New feature (non-breaking change which adds or improves functionality)
- [ x] I have read the [**CONTRIBUTING**](https://github.com/e3nn/e3nn/blob/main/CONTRIBUT …
> Add Bessel Basis

- INSTALL.md
- docs/examples/tetris_polynomial.rst
- docs/guide/equivar_testing.rst
- docs/guide/jit.rst
Fixes some warnings in the sphinx build output, from incorrect syntax / bad references / wrong line numbers.
Preparing to work on #228 and wanted to fix existing warnings before making further changes.
Sphinx builds locally. I haven't checked the output but I am confident it should be fixed, from my knowledge of rST.
> Fix warnings in docs.

- .gitignore
Tiny change to `.gitignore` that will make my life as a developer easier.
This ignores `*.so` so that CUDA libraries built in-place are ignored by git.
Small quality of life enhancement.
> Ignore *.so (cuda libraries built in-place).

- ChangeLog.md
- e3nn/o3/_irreps.py
- tests/o3/irreps_test.py
- Minor improvements to Irrep/Irreps docs and implementation.
- Add test for empty Irreps.
This started as an attempt to change `Irrep` / `Irreps` so that they weren't subclassed from `tuple`, but that failed because of issues with TorchScript. These classes are too complex to be written as TorchScript-compatible classes, so instead I pivoted to making some minor improvements to the class's docs, implementation, and testing.
Additional context in PR comments.
Existing tests pass, new tests added.
> Irreps improvements

- ChangeLog.md
- e3nn/o3/_tensor_product/_tensor_product.py
- tests/o3/tensor_product_test.py
Adds `weight_views` and `weight_view_for_instruction` to `TensorProduct`.
This makes it easier to investigate/initialize the weights of a `TensorProduct` while hiding the specifics of the flattened weight storage from the user, enabling easier future changes if necessary.
e3nn test suite, some new tests
I updated the Xavier initialization doctest to use this and for some reason cannot get it to pass. The same code when run on its own produces no output and no errors.
> Weight view methods in `TensorProduct`

- ChangeLog.md
- e3nn/nn/_extract.py
Fix docs for ```ExtractIr```
Docs currently ask for 
```
ir : list of `Irrep`
representation to extract
```
but the code convert this to a `Irrep`: 
```
ir = o3.Irrep(ir)
```
So if one actually passes a list of `Irrep` it fails: 
```
>>> from e3nn.nn import ExtractIr
>>> from e3nn import o3
>>> irs = o3.Irreps('0e + 1o')
>>> ir = [o3.Irreps('0e')]
>>> extract_ir = ExtractIr(irreps_in=irs, ir=ir)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/simonbatzner1/Desktop/Research/Research/Research_Code/e3nn/e3nn/nn/_extract.py", line 89, in __init__
ir = o3.Irrep(ir)
File "/Users/simonbatzner1/Desktop/Research/Research/Research_Code/e3nn/e3nn/o3/_irreps.py", line 72, in __new__
assert isinstance(l, int) and l >= 0, l
AssertionError: [1x0e]
```
instead it …
> Fix ExtractIr docs

- ChangeLog.md
- e3nn/o3/_tensor_product/_codegen.py
Previously, `_codegen` used `torch.randn` to build example inputs when calling `opt_einsum_fx`. This affects the PyTorch RNG state and causes results to change depending on whether einsum optimization is enabled.
This PR replaces those `randn` calls with `zeros` (which should also be faster) to avoid contaminating the RNG state; a global optimization option should never substantively affect results.
e3nn test suite (locally, with opt_einsum_fx instaled), reproducability testing with our networks.
> Fix opt_einsum RNG bug

- e3nn/util/codegen/_eval.py
As per Mario Geiger and Alby M's suggestion, this uses a fixed filename for the temporary code, but in a temporary directory.
> Avoids re-entrant file opening for Windows

- ChangeLog.md
- docs/api/o3/o3_tp.rst
- e3nn/o3/_linear.py
- e3nn/util/test.py
- tests/defaults_test.py
- tests/o3/linear_test.py
- tests/o3/tensor_product_sub_test.py
Optimized code for `o3.Linear` to avoid allocation/contraction with a tensor of ones of equal size to the features. This approximately halves the forward memory & compute requirements of `o3.Linear`.
Simple CPU benchmark:
```python
from torch.utils.benchmark import Timer
ir = "16x0o + 16x0e + 16x1o + 16x1e + 16x2o + 16x2e"
l_slow = SlowLinear(ir, ir)
l = Linear(ir, ir)
n = 2000
inps = [l.irreps_in.randn(200, -1) for _ in range(n + 100)]
inps_iter_fast = iter(inps)
inps_iter_slow = iter(inps)
t_slow = Timer(stmt="out = l_slow(next(inps_iter_slow))", globals={'l_slow': l_slow, 'inps_iter_slow': inps_iter_slow})
t_slow.timeit(n)
t_fast = Timer(stmt="out = l(next(inps_iter_fast))", globals={'l': l, 'inps_iter_fast': inps_iter_fast})
t_fast.timeit(n)
```
Approximately one-third speedup. …
> Optimized code for `o3.Linear`

- ChangeLog.md
- e3nn/nn/_gate.py
- e3nn/o3/_irreps.py
- e3nn/o3/_linear.py
- e3nn/o3/_tensor_product/_codegen.py
- examples/tensor_product_benchmark.py
- tests/o3/linear_test.py
- tests/o3/tensor_product_test.py
Specialized code for some special cases:
- No `torch.cat` copy if `len(irreps_out)` is 1 (TensorProduct and Linear)
- No view creation if `len(irreps_in) == 1` (Linear)
- Specialized code for `uuu`
- Specialized cross-product code for `uuu`
- Specialized code for unweighted `uvv`
Some benchmarks:
For a `Gate`-like elementwise tensor product with scalars, specialized code for `uuu` (opt einsum is on):
```
python examples/tensor_product_benchmark.py -n 5000 --elementwise --specialized-code False --opt-ein True --irreps-in2 32x0e
221.65 us
1 measurement, 5000 runs , 1 thread
 
--specialized-code True
139.54 us
1 measurement, 5000 runs , 1 thread
```
For a `uuu` cross product:
```
python examples/tensor_product_benchmark.py -n 1000 --elementwise --irreps 32x1o --irreps-out 32x1e …
```
> Extra specialized code

- e3nn/util/_argtools.py
Make `_argtools._transform`, which is used internally by `equivariance_error`, automatically move the translation + rotation tensors to the same device as the data being transformed.
Make equivariance testing posible on GPU.
- e3nn tests
- use in code
> Fix GPU device issue in equivariance testing

- ChangeLog.md
- e3nn/nn/_normact.py
- e3nn/o3/_norm.py
- tests/nn/normact_test.py
- tests/o3/norm_test.py
- Corrected `epsilon` in `NormActivation` to avoid gradient NaNs
- Option to return squared norms in `o3.Norm`.
- ReLU trick from @mariogeiger to avoid gradient issues in `o3.Norm` at zero
This updated option now correctly reproduces `norm_with_epsilon` from TFN (https://github.com/tensorfieldnetworks/tensorfieldnetworks/blob/master/tensorfieldnetworks/utils.py#L22) and avoids, to the extend possible with norm nonlinearities, the gradient/asymptote issues at zero.
- e3nn test suite
- new tests
- resolved issue in real world network
> Fix `NormActivation` NaN gradients; `squared` for `Norm`

- ChangeLog.md
- e3nn/util/_argtools.py
- e3nn/util/jit.py
- tests/util/test_jit.py
Fix `_get_tracing_inputs` to guess the dtype of a module, as well as its device, so that modules with dtypes different than the current default dtype can still be compiled. (E.g. models loaded from another process with a different default dtype.)
> Fix trace compile with dtypes

- e3nn/util/_argtools.py
Use [`.is_floating_point()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.is_floating_point) instead of the `_FLOATING_TYPES` hack; this should in theory fix edge cases we haven't seen yet for strange floating point types like `float16`, `tensorfloat32` (NVIDIA Ampere), etc. It's also just cleaner + more correct.
> Use `.is_floating_point()`

- ChangeLog.md
- docs/guide/equivar_testing.rst
- docs/guide/normalization.rst
- e3nn/nn/_activation.py
- e3nn/util/_argtools.py
- e3nn/util/test.py
- tests/nn/activation_test.py
- tests/nn/gate_test.py
- tests/nn/normact_test.py
- tests/o3/linear_test.py
- tests/o3/tensor_product_test.py
- tests/util/test_test.py
Done:
- Avoid `torch.cat` when unneeded in `Activation`
- More tests for `Activation`
- Added `assert_normalized` and use for various modules
- Weight support in `assert_normalized`
- `assert_normalized` for `Linear`, `TensorProduct` tests
e3nn tests
> Normalization testing; small `Activation` improvement

- .github/workflows/tests.yml
- ChangeLog.md
- INSTALL.md
- docs/requirements.txt
- e3nn/nn/_extract.py
- e3nn/o3/_angular_spherical_harmonics.py
- e3nn/o3/_linear.py
- e3nn/o3/_reduce.py
- e3nn/o3/_tensor_product/_codegen.py
- e3nn/o3/_tensor_product/_tensor_product.py
- e3nn/util/codegen/_eval.py
- e3nn/util/codegen/_mixin.py
- setup.py
- tests/nn/extract_test.py
- tests/nn/models/gate_points_2101_test.py
- tests/o3/tensor_product_test.py
Initial work on FX-only codegen:
Issues remaining:
e3nn test suite
> FX-only codegen

- ChangeLog.md
- e3nn/o3/_spherical_harmonics.py
- e3nn/util/test.py
- examples/tetris_gate.py
- examples/tetris_polynomial.py
- tests/o3/cartesian_spherical_harmonics_test.py
- tests/o3/linear_test.py
- tests/o3/tensor_product_test.py
- Fixed accuracy metric for tetris examples (accuracy should be how many shapes are correctly classified, not how many rounded one-hot labels are right)
- Print more info in tetris examples
- Make `format_equivariance_error` public
- Add some more comprehensive tests to `o3.SphericalHarmonics`
- Add `assert_equivariant` to tetris examples as a demonstration of the full-featured way to test equivariance
e3nn tests
> Small tetris example improvements; related fixes

- ChangeLog.md
- e3nn/o3/_irreps.py
- e3nn/o3/_linear.py
- e3nn/o3/_tensor_product/_codegen.py
- e3nn/o3/_tensor_product/_tensor_product.py
- tests/o3/linear_test.py
- tests/o3/tensor_product_test.py
- Allow instructions to be specified to `o3.Linear` to mix only certain irreps
- Weight view methods for `o3.Linear`
- Fix zero multiplicities for TensorProduct
- Make weight views support `shared_weights=False`
Previously, there was no public way to interpret the `.weight` of an `o3.Linear`, since the order of paths was not exposed.
e3nn tests
> Instructions for `o3.Linear`; zero multiplicities fix

- e3nn/nn/models/v2103/gate_points_networks.py
I have moved the geometric preprocessing step in the forward of SimpleNetwork to a `preprocess` method.
This allows for easy modification of SimpleNetwork for e.g. crystal systems because the method can be easily overwritten.
The behavior of SimpleNetwork is identical, only the organization has changed.
> SimpleNetwork -- move preprocessing to method for easy overwriting

- .github/workflows/tests.yml
- docs/conf.py
Added code in `conf.py` to autogenerate links to code definitions.
I wanted to be able to link directly from the API docs to github code.
I have successfully run `make html` with these changes and the docs look as desired.
> add linkcode to docs

- e3nn/o3/_irreps.py
spherical harmonics method in irreps was missing even parity.
Added p=-1 as a default argument.
Added example:
>>> Irreps.spherical_harmonics(4,1)
1x0e+1x1e+1x2e+1x3e+1x4e
> Added parity of 1 to the spherical harmonics representation method.

- examples/tensor_product_benchmark.py
- examples/tensor_product_profile.py
1. Workaroud for profiler hanging on certain CUDA drivers, see https://github.com/pytorch/kineto/issues/126
2. Use `tanh()` to force pytorch to realize the backwards gradient of the sum by making it value dependent (this prevents false performance numbers if performance would be significantly different for a zero-stride expanded gradient tensor)
Ran it.
> Small bugfixes for profiling

- .pre-commit-config.yaml
- .pylintrc
- CONTRIBUTING.md
- ChangeLog.md
- e3nn/io/_cartesian_tensor.py
- e3nn/io/_spherical_tensor.py
- e3nn/math/_normalize_activation.py
- e3nn/math/_soft_one_hot_linspace.py
- e3nn/math/_soft_unit_step.py
- e3nn/math/perm.py
- e3nn/nn/_batchnorm.py
- e3nn/nn/_dropout.py
- e3nn/nn/_extract.py
- e3nn/nn/_fc.py
- e3nn/nn/_identity.py
- e3nn/nn/_s2act.py
- e3nn/nn/models/v2103/gate_points_networks.py
- e3nn/nn/models/v2103/points_convolution.py
- e3nn/o3/_angular_spherical_harmonics.py
- e3nn/o3/_irreps.py
- e3nn/o3/_linear.py
- e3nn/o3/_reduce.py
- e3nn/o3/_spherical_harmonics.py
- e3nn/o3/_tensor_product/_codegen.py
- e3nn/o3/_tensor_product/_tensor_product.py
- e3nn/util/codegen/_mixin.py
- e3nn/util/default_type.py
- e3nn/util/jit.py
- e3nn/util/test.py
- setup.py
Quality of life improvements.
* Added pre-commit hook that allows users to do `pre-commit install` and
flake8 will be run each time a commit is made
* Added 'dev' extra to e3nn.  This allows ones to do `pip install -e
.[dev]` and automatically get pytest and pre-commit (for now).  The idea
is that you automatically install libraries that everyone doing
development should have.
* Added full instructions for the pre-commit hook and running of test to
CONTRIBUTING.md
* Added a few missing type hints that I came across
This makes automated checking during development easier and more transparent.
All tests pass.
N/A
> Added pre-commit hook and some missing types

- e3nn/util/test.py
- examples/conftest.py
- tests/conftest.py
This fixture will automatically set the python, numpy and torch seeds
before running each test in the hope of being able to get some
reprodicibility.  There are certain module in torch that may mean the
tests are not 100% identical each time, but for the most part this
should already help with randomly failing tests.
A fixture that sets seeds for all tests in `tests/` and `examples/`.
Because the tetris test was sometimes randomly failing.
Tested locally
> Added pytest fixture that sets seeds before tests

- ChangeLog.md
- docs/api/o3/o3_sh.rst
- e3nn/o3/_linear.py
- e3nn/o3/_norm.py
- e3nn/o3/_tensor_product/_codegen.py
- e3nn/o3/_tensor_product/_tensor_product.py
- tests/o3/linear_test.py
- tests/o3/tensor_product_test.py
- add `path_normalization` that can take values `element` or `path`
- rename `normalization` into `irrep_normalization`
> path_normalization for TensorProduct

- ChangeLog.md
- e3nn/__init__.py
- e3nn/nn/models/v2103/voxel_convolution.py
- e3nn/nn/models/v2104/voxel_convolution.py
- e3nn/o3/_linear.py
- e3nn/o3/_tensor_product/_codegen.py
- e3nn/o3/_tensor_product/_tensor_product.py
- e3nn/util/codegen/_mixin.py
- e3nn/util/jit.py
- tests/defaults_test.py
- tests/o3/tensor_product_test.py
- split codegen in two: `left_right` and `right`
- add flags `compile_left_right` and `compile_right` to `TensorProduct`
- set default `optimize_einsums=False`
- add new global flag `jit_script_fx=False` that by default turns of the `torch.jit.script` of `fx` code
> Compile minimum stuff

- .github/workflows/tests.yml
Don't install unneeded torchvision and torchaudio
No reason to waste CI time installing dependencies that are never used by e3nn.
> Faster CI tests

- docs/guide/periodic_boundary_conditions.rst
Updated `torch.einsum('ni,nij->j'` to `torch.einsum('ni,nij->nj'` in the calculation of `edge_vec` with periodic boundary conditions described in the documentation.
Preserves the batch dimension when applying a lattice vector shift to the edge vector rather than contracting along the batch dimension.
There were no changes made to the code, just updates to the example described in the documentation.
> Update calculation of edge_vec with periodic boundary conditions.

- ChangeLog.md
- e3nn/io/_cartesian_tensor.py
- e3nn/o3/_reduce.py
- tests/o3/reduce_tensor_test.py
```python
irreps = CartesianTensor("ij=-ji")
rtp = irreps.reduced_tensor_products()
irreps.from_cartesian(data, rtp=rtp)  # use rtp
irreps.from_cartesian(data)  # create a new ReducedTensorProducts at each call
```
> Remove CartesianTensor._rtp

- ChangeLog.md
- e3nn/util/test.py
> Let equivariance error methods tell which argument led to errors

- ChangeLog.md
- e3nn/util/_argtools.py
- e3nn/util/test.py
Transform tensors for the equivariance test in `float64`.
Removes (to a greater extent) the test itself as a possible source of equivariance error. For testing a float32 network, this means that the transformations for the _test_ are effectively exact and all equivariance error will come from the function itself.
- X ] I have read the [**CONTRIBUTING**](https://github.com/e3nn/e3nn/blob/main/CONTRIBUTING.md) document.
> Do the transform for the equivariance test in float64

- ChangeLog.md
- e3nn/util/_argtools.py
- e3nn/util/test.py
- do the difference and error comparison in float64 too
- detach things from the autograd graph to free memory when testing models
> dtype and autograd fixes for equivariance_error

- e3nn/o3/_tensor_product/_codegen.py
- e3nn/o3/_tensor_product/_tensor_product.py
Provide a private API to register alternative tensor product codegen providers. If a provider doesn't support given parameters, it just returns `None` and the code tries the next with the default full-featured one as final fallback.
**TODO**: a more generic way of dealing with optimization parameters than the explicit `optimize_einsums` and `specialized_code` parameters
Let us work on optimization without having to maintain branches that get out of sync with `main`.
> add codegen registration

- ChangeLog.md
- e3nn/o3/_wigner.py
Make sure that `wigner_3j`  _always_ returns a contiguous copy regardless of dtype or device
Previously it would fail to on device cpu and dtype default, since then unless you say otherwise `.to()` defaults to preserving memory layout.
> wigner_3j always contiguous

- .github/workflows/tests.yml
- .gitignore
- ChangeLog.md
- e3nn/nn/_activation.py
- e3nn/o3/_irreps.py
- e3nn/o3/_reduce.py
- e3nn/o3/_tensor_product/_sub.py
- e3nn/o3/_tensor_product/_tensor_product.py
- tests/o3/irreps_test.py
Changed a bunch of asserts to exceptions.  Asserts are best used to check for internal errors when `e3nn` itself does something it didn't expect to do.  However, they were frequently used to do things like report incorrect function parameters in which case it is more common to emit `TypeError` or `ValueError`.
I've also updated `TensorProduct.visualize` to work even if it is located on the GPU.
* Code has become more pythonic
* `TP.visualize` is now more usable.
* Added tests for incorrect values passed to `Irrep`/`Irreps`.
> Minor quality of life improvements

- e3nn/nn/_batchnorm.py
_batchnorm torch.cat empty Tensors
if self.training and not self.instance:
if len(new_means) > 0:
torch.cat(new_means, out=self.running_mean)
if len(new_vars) > 0:
torch.cat(new_vars, out=self.running_var)
Resolves: #???
```
ckages/e3nn/o3/_spherical_harmonics.py:82: UserWarning: FALLBACK path has been taken inside: compileCudaFusionGroup. This is an indication that codegen Failed for some reason.                                          
To debug try disable codegen fallback path via setting the env variable `export PYTORCH_NVFUSER_DISABLE=fallback`                                                                                                        
To report the issue, try enable logging via setting the envvariable ` export PYTORCH_JIT_LOG_LEVEL=manager.cpp` …
```
> fix _batchnorm

- e3nn/nn/models/v2106/gate_points_networks.py
Allows automatic incrementing of edge indexes when combining multiple graphs for a mini-batch.
Update edge specification in pytorch-geometric.Data to use 'edge_index' as opposed to 'edge_src' and 'edge_dst'. This allows for automatic incrementing of edge indexes when combining multiple graphs into a single disconnected graph when creating a mini-batch. This is also the standard way of using pytorch-geometrics Data/DataLoader classes. See [here](https://pytorch-geometric.readthedocs.io/en/latest/advanced/batching.html) for more information on pytorch-geometric's mini-batching.
Removes the need to write a custom DataLoader when using NetworkForAGraphWithAttributes to do the edge incrementing yourself.
Ran test function in gate_points_networks.py. Tested on personal dataset with meshes as …
> Update NetworkForAGraphWithAttributes to use the standard pytorch-geometric field for specifying edges.

- e3nn/o3/_tensor_product/_codegen.py
Using expand() instead of broadcast_to() for ONNX exportability
broadcast_to() is documented as identical to expand(), but is not currently supported by ONNX exporter.
Resolves: #???
> Using expand() instead of broadcast_to() for ONNX exportability

- ChangeLog.md
- e3nn/nn/_batchnorm.py
- e3nn/o3/_tensor_product/_sub.py
- examples/s2cnn/mnist/gendata.py
- examples/s2cnn/mnist/train.py
- tests/o3/cartesian_spherical_harmonics_test.py
With this pull request, the scalar bias term in `_batchnorm.py` can be enabled or disabled (separately from `self.weight`) as desired.
When one does not provide scalar inputs to `BatchNorm`, the `self.bias` term becomes an unused network parameter that should be removed.
I have installed a local copy of this fork and successfully found that I can now remove the bias term for scalar inputs as desired (e.g., in the context of not providing any scalar inputs in the first place).
> Make scalar bias term optional in `_batchnorm.py`

- .github/workflows/tests.yml
- .readthedocs.yml
- docs/requirements.txt
- pyproject.toml
> Fixing broken tests in #437

- e3nn/o3/experimental/_elementwise_tp.py
- e3nn/o3/experimental/_full_tp.py
- tests/o3/experimental/test_elementwise_tp.py
- tests/o3/experimental/test_fulltp.py
Sorry these checks got missed in the first round. Found some bugs in elementwise and fulltp
- irreps_out was wrong
- irreps with same parity were overwriting the same path
@mariogeiger
> Irreps assert in `o3.experimental`

- e3nn/o3/_tensor_product/_tensor_product.py
Updated code to use `matplotlib.colormaps["Blues"]` as `matplotlib.cm.get_cmap()` is deprecated (see https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.7.0.html#deprecation-of-top-level-cmap-registration-and-access-functions-in-mpl-cm )
Resolves: #474
> update deprecated matplotlib option

- .github/workflows/tests.yml
Syncing up with python version tested in e3nn-jax
> Bump python version to only 3.11 in tests

- e3nn/math/_normalize_activation.py
In line 17 of `e3nn/math/_normalize_activation.py`, I changed from 
https://github.com/e3nn/e3nn/blob/8c9891dbce85a2fd0ec25bc95f8d81c3c6619d3e/e3nn/math/_normalize_activation.py#L17
to
```python
z = torch.randn(1_000_000, generator=gen, dtype=torch.float64, device="cpu").to(dtype=dtype, device=device)
```
**Background**: I'm using E3NN in a training code written with pytorch-lightning. During the training process, I encountered the following error:
```python
File "/opt/conda/lib/python3.10/site-packages/e3nn/nn/_fc.py", line 73, in __init__
act = normalize2mom(act)
File "/opt/conda/lib/python3.10/site-packages/e3nn/math/_normalize_activation.py", line 43, in __init__
cst = moment(f, 2, dtype=torch.float64, device="cpu").pow(-0.5).item()
File …
```
> explicitly specify device placement in random number generator in e3nn.math._normalize_activation.moment

- e3nn/o3/_irreps.py
Remove the unnecessary for loop over multiplicities when using the function D_from_angles in the Irreps class.
Line 743 in _irreps.py `direct_sum(*[ir.D_from_angles(alpha, beta, gamma, k) for mul, ir in self for _ in range(mul)])` performs a for loop over multiplicities which in each iteration calculates `ir.D_from_angles` even though the result is the same each time. The suggested change calculates `D_from_angles` only once per irrep and repeats the resulting block according to the multiplicity.
The change significantly increases the speed of the function especially in scenarios, where the number of multiplicities is high.
The changes were tested by comparing the results of old and new implementation on an irreps object `Irreps("128x0e + 64x1o + 16x2e + 4x3o + 1x4e")` for random tensors …
> Remove for loop over multiplicities in D_from_angles
