e3nn/e3nn

- e3nn/kernel.py
- e3nn/kernel_mod.py
- e3nn/networks.py
- e3nn/point/kernelconv.py
- e3nn/rs.py
- e3nn/tensor_product.py
- tests/kernel_test.py
- tests/normalization_test.py
- tests/point/kernelconv_test.py
- tests/tensor_product_test.py
This pull request is on top of #45
> tensor_product(input1, input2, output)

- e3nn/kernel_mod.py
- e3nn/linear_mod.py
- e3nn/rs.py
- examples/point/tetris.py
new functions:
- `kernel_geometric` create mixing matrix for the geometric kernel
- `kernel_linear` create the mixing matrix for the linear kernel
new classes:
- `KernelLinear` module for a linear kernel
> Split kernel_mod

- e3nn/batchnorm.py
- e3nn/kernel.py
- e3nn/networks.py
- e3nn/o3.py
- e3nn/rs.py
- e3nn/tensor_product.py
- tests/tensor_product_test.py
PR on top of #65 
This PR is not important to read.
I created it so you have less to read in #65.
> TensorSquare and more stuff

- e3nn/kernel.py
- e3nn/kernel_mod.py
- e3nn/o3.py
- e3nn/point/kernelconv.py
- e3nn/rsh.py
- e3nn/s2grid.py
- e3nn/spherical_harmonics.py
- e3nn/spherical_tensor.py
- e3nn/util/plot.py
- examples/plot_kernels.py
- examples/point/gravity.py
- tests/equivariance_test.py
- tests/import_test.py
- tests/o3_test.py
- tests/point/kernelconv_test.py
- tests/spherical_tensor_test.py
- new file `rsh.py` for Real Spherical Harmonic
- all functions request list of L's  (to simplify the code, sorry user)
- all functions request pytorch tensor (to simplify the code, sorry user)
- home-made computation using legendre (stop using lie_learn)
- remove `backward` version but use backwadable code when input requires grad
> Big changes in spherical harmonics

- e3nn/networks.py
- e3nn/tensor/__init__.py
- tests/equivariance_test.py
- tests/networks_test.py
@mariogeiger let me know how you want to format long lines for doc strings.
> add doc strings to some network classes and remove feature_product

- .github/workflows/pull_request.yml
- e3nn/tensor/fourier_tensor.py
- e3nn/tensor/spherical_tensor.py
Example
```python
from e3nn.tensor import SphericalTensor
import plotly.graph_objects as go
x = SphericalTensor(torch.randn(4))
surface = go.Surface(**x.plotly_surface())
fig = go.Figure(data=[surface])
fig.show()
```
> SphericalTensor.plotly_surface

- .github/workflows/pull_request.yml
- .github/workflows/push.yml
I noticed my tests failed on #151 and #152. This PR (hopefully) fixes the CI issues caused by pip 20.3's new, stricter resolution logic.
See this upstream issue where I commented for more details:
https://github.com/rusty1s/pytorch_geometric/issues/1876
> Pin pip to 20.2.4.

- e3nn/point/data_helpers.py
I improved some docstrings in `data_helpers.py` to clarify some information that wasn't clear to me about neighbor finding.
I'm guessing the standard is Google-style docstrings (`Args:`) based on the rest of the code base, but there are some Sphinx-style `:param name:` mixed in.
Let me know if you prefer another way.
Thanks!
> Rewrite docstrings and add missing parameters for neighbor list methods.

- .gitignore
- INSTALL.md
- doc/Makefile
- doc/api/api.rst
- doc/api/image.rst
- doc/api/networks.rst
- doc/api/non_linearities.rst
- doc/api/o3.rst
- doc/api/point.rst
- doc/api/rs.rst
- doc/api/rsh.rst
- doc/api/tensor.rst
- doc/conf.py
- doc/index.md
- doc/installation.md
- doc/make.bat
- doc/requirements.txt
This PR adds Sphinx docs for the existing set of modules (excluding `util`).
> Add Sphinx docs.

- README.md
- code_of_conduct.md
Addresses https://github.com/e3nn/e3nn/issues/170
> add code of conduct from contributor-convenant and link in README

- e3nn/io/cartesian_tensor.py
- e3nn/math/group/reduce.py
- e3nn/o3/reduce.py
- tests/reduce_tensor_test.py
```python
tp = o3.ReducedTensorProducts('ijk=-jik', i="5x1e", k="2o")
tp(torch.randn(5 * 3), torch.randn(5 * 3), torch.randn(5))
torch.einsum('oijk,i,j,k->o', tp.change_of_basis, torch.randn(5 * 3), torch.randn(5 * 3), torch.randn(5))
```
> ReducedTensorProducts

- e3nn/io/cartesian_tensor.py
- e3nn/io/spherical_tensor.py
- e3nn/o3/irreps.py
- Change the first argument to cls, following the conventions
- Change explicit superclass access to super() call
This will close e3nn/e3nn#184.
> Update __new__ methods

- docs/api/nn/nn_normact.rst
(Couldn't re-open #185 for some reason, sorry for extra PR.)
> Added norm-based nonlinearity to docs

- .github/workflows/tests.yml
- e3nn/util/jit.py
Fix flake8 error E713: test for membership should be 'not in'
> Fix E713: test for membership should be 'not in'

- e3nn/nn/extract.py
- tests/nn/extract_test.py
- Made `Extract`/`ExtractIr` more efficiently auto-JITable — there's no need to make tracing inputs
- Added tests for `Extract` and `ExtractIr`
> `Extract` tests

- docs/guide/guide.rst
- docs/guide/jit.ipynb
Added a tutorial on TorchScript support. (Documentation for my PR #197).
> Documentation for TorchScript

- docs/api/e3nn.rst
- docs/api/io/spherical_tensor.rst
- docs/api/nn/models/gate_points_2101.rst
- docs/api/nn/models/v2103.rst
- docs/api/o3/o3_sh.rst
- docs/api/o3/o3_tp.rst
- docs/guide/normalization.rst
- e3nn/nn/batchnorm.py
- e3nn/nn/fc.py
- e3nn/o3/irreps.py
- e3nn/o3/rotation.py
- e3nn/o3/s2grid.py
- e3nn/o3/wigner.py
I read through the documentation while familiarizing myself with the new API. I took note of a few typos and sentences that I didn't understand at first. I tried to rewrite the confusing sentences in a clearer way.
Improves project documentation.
*Note:* I typically don't update project changelogs for small documentation changes like this, so I skipped that.
> Documentation fixes.

- e3nn/o3/tensor_product/_codegen.py
Some small fixes and updates for the `fx` branch to make it compatible with the latest `opt_einsum_fx`
> Small fx fixes

- ChangeLog.md
- docs/api/math/soft_heaviside.rst
- e3nn/math/__init__.py
- e3nn/math/soft_heaviside.py
- tests/math/soft_unit_step_test.py
I want to implement the function
```
Theta(x) exp(-1/x)
```
where `Theta` is the [Heaviside](https://en.wikipedia.org/wiki/Heaviside_step_function) function.
Useful as an envelope function because it zero for `x <= 0` and converges to one when `x -> infty` while being infinitely differentiable everywhere.
It is often used as a function that is `C^\infty` but non analytical.
`pytorch` has trouble differentiating it at `x=0` obviously...
> [need help] soft_unit_step

- e3nn/o3/tensor_product/_codegen.py
- examples/tensor_product_benchmark.py
> Small things: `--irreps` options for TP benchmark; graph linting in codegen to catch problems

- e3nn/o3/tensor_product/tensor_product.py
Improves TensorProduct.right documentation. I didn't fully understand what the method did or how to use its result. @blondegeek gave a helpful explanation and suggested these improvements.
Resolves: #235
(Paste screenshot of docs here)
> Expand "TensorProduct.right" documentation.

- ChangeLog.md
- INSTALL.md
- e3nn/__init__.py
- e3nn/o3/_tensor_product/_tensor_product.py
- tests/defaults_test.py
- Added `opt_einsum_fx` to the ChangeLog for the previous version (where it was released)
- Added `opt_einsum_fx` to `INSTALL.md`
- Linked more general PyTorch install instructions in `INSTALL.md`
- Added `e3nn.set_optimization_defaults()` and `e3nn.get_optimization_defaults()` for setting global default optimization settings
e3nn test suite
> `opt_einsum_fx` toggle and docs

- ChangeLog.md
- e3nn/o3/_norm.py
- e3nn/o3/_tensor_product/_tensor_product.py
Explicit `in1_var`, `in2_var`, `out_var` parameters replacing the old awkward format.
e3nn tests
> Explicit `in1_var`, `in2_var`, `out_var` parameters

- e3nn/nn/_gate.py
- e3nn/o3/_tensor_product/_tensor_product.py
I suggested some doc changes on Slack and this PR implements those changes. Feel free to reject or modify any changes if they're unclear or incorrect.
> Improve tensor product docs.

- e3nn/o3/_tensor_product/_tensor_product.py
Param names in docstring hadn't been updated.
> Update param names in TP docs

- e3nn/o3/_reduce.py
- e3nn/util/_argtools.py
- tests/util/test_jit.py
> Fix `_argtools` issue introduced with ReducedTensorProducts

- docs/api/o3/o3_tp.rst
- e3nn/o3/_tensor_product/_tensor_product.py
- e3nn/util/test.py
- Update typo about color in TP visualization after discussion in the slack
- More details on how the different tensor products mix paths
- Some small things
- Some lint in `test.py` that my editor fixed automatically
> Small TP docs additions and fixes

- ChangeLog.md
- e3nn/o3/_tensor_product/_codegen.py
- tests/o3/tensor_product_test.py
Specialized code for `uuw`, based on the specialized code for `uvv`
Added more cases to existing test
> `uuw` specialized code

- docs/conf.py
- docs/examples/periodic_boundary_conditions.rst
- docs/guide/guide.rst
- docs/guide/periodic_boundary_conditions.rst
- docs/requirements.txt
I've added an example for how handle periodic boundary conditions for batches of graph objects including an example network.
I've been asked several times for such an example 😅
I'm able to compile the docs locally and it looks as expected.
> Added example for periodic boundary conditions (e.g. crystals)

- ChangeLog.md
- e3nn/o3/_linear.py
- e3nn/o3/_tensor_product/_codegen.py
- tests/o3/tensor_product_sub_test.py
> TP Normalization

- ChangeLog.md
- docs/api/o3/o3_tp.rst
- e3nn/o3/__init__.py
- e3nn/o3/_tensor_product/__init__.py
- e3nn/o3/_tensor_product/_tensor_product.py
- tests/o3/tensor_product_sub_test.py
> tensor square

- ChangeLog.md
- e3nn/io/_cartesian_tensor.py
When `rtp` is not passed, generate one with correct device and dtype.
Locally with a GPU available and used.
> CartesianTensor dtype fixes

- ChangeLog.md
- e3nn/o3/__init__.py
- e3nn/o3/_wigner.py
- e3nn/util/test.py
- tests/o3/wigner_test.py
Use the [change of basis from real to complex](https://en.wikipedia.org/wiki/Spherical_harmonics#Real_form) given by the wikipedia page of the spherical harmonics to compute the clebsch-gordan coefficient of so3 from the [clebsch-gordan coefficient of su2 given by the qutip library](https://qutip.org/docs/3.1.0/apidoc/functions.html#qutip.utilities.clebsch).
This imply a change of sign for the clebsch-gordan coefficients for some triplet.
This is due to the fact that in main, the way to fix the sign of the cg was arbitrary. Using qutip cg fixes this arbitrariness.
```
l1,l2,l3=(1,2,2): main == -qutip
l1,l2,l3=(1,3,3): main == -qutip
l1,l2,l3=(1,4,4): main == -qutip
l1,l2,l3=(1,5,5): main == -qutip
l1,l2,l3=(1,6,6): main == -qutip
l1,l2,l3=(1,7,7): main == -qutip
l1,l2,l3=(1,8,8): main == …
```
> cg from qutip

- docs/guide/irreps.rst
> Fixed a typo

- docs/api/o3/o3_sh.rst
- e3nn/io/_spherical_tensor.py
- e3nn/nn/_activation.py
- e3nn/nn/_batchnorm.py
- e3nn/nn/_fc.py
- e3nn/nn/_s2act.py
- e3nn/nn/_so3act.py
- e3nn/nn/models/gate_points_2101.py
- e3nn/nn/models/gate_points_2102.py
- e3nn/nn/models/v2103/conv_points_in_out.py
- e3nn/nn/models/v2103/gate_points_networks.py
- e3nn/nn/models/v2103/voxel_convolution.py
- e3nn/nn/models/v2104/voxel_convolution.py
- e3nn/o3/_angular_spherical_harmonics.py
- e3nn/o3/_irreps.py
- e3nn/o3/_reduce.py
- e3nn/o3/_rotation.py
- e3nn/o3/_s2grid.py
- e3nn/o3/_so3grid.py
- e3nn/o3/_tensor_product/_sub.py
- e3nn/o3/_wigner.py
- e3nn/util/_argtools.py
- e3nn/util/test.py
- examples/conftest.py
- examples/s2cnn/mnist/gendata.py
- examples/s2cnn/mnist/train.py
- tests/o3/tensor_product_test.py
- tests/util/test_jit.py
Adds type annotations to various places
This facilitates static analysis, reducing CI issues and error rates.
> Add type annotations

- .github/CHANGELOG.md
- .github/workflows/tests.yml
This PR aims to decrease the CI time, by enabling `pip` caching in CI.
Request for Review: @mariogeiger 
Builds on top of the work done in #425 #426 #429, mirrors https://github.com/e3nn/e3nn-jax/pull/58
> feat(ci): enable pip cache in CI

- .github/CHANGELOG.md
- e3nn/o3/__init__.py
- e3nn/o3/_irreps.py
- e3nn/o3/experimental/__init__.py
- e3nn/o3/experimental/_full_tp.py
- e3nn/util/datatypes.py
- tests/o3/experimental/benchmark_pt2.py
- tests/o3/experimental/test_fulltp.py
- tests/o3/experimental/test_tp.py
@mariogeiger @Linux-cpp-lisp Would appreciate a review. Also let me know what other tests I can add to `tests/o3/experimental/test_fulltp.py`
Linear coming in next !
> `o3.experimental.FullTensorProductv2` for `torch.compile(...., fullgraph=True)`

- docs/requirements.txt
- e3nn/o3/_tensor_product/_tensor_product.py
The docs build issue was stemming from conflicting versions between torch and torch-geometric so pinned it on 2.4.0 for now. Thanks @mariogeiger for the suggestion !
> Fix docs build

- .github/workflows/release.yml
Syncing the versions to match e3nn-jax (with the hope that the token issue in release goes away)
> updating versions for release actions

- pyproject.toml
Added `content-type = "text/markdown"` to `tool.setuptools.dynamic` which triggers pypi to render images, animations and links as expected.
Resolves: #482 
Verified that this change produces right behaviour on the [testpypi index.](https://test.pypi.org/project/e3nn-docfix/0.5.3.1/)
- [ x ] I have read the [**CONTRIBUTING**](https://github.com/e3nn/e3nn/blob/main/.github/CONTRIBUTING.md) document.
- [ x ] My code follows the code style of this project.
> Small change to pyproject.toml to fix pypi docs

- .github/workflows/style.yaml
- .github/workflows/tests.yml
- e3nn/math/_reduce.py
- e3nn/math/perm.py
Who let the Rust out ruff ruff....
> Replace flake8 with ruff 
